group: travis_latest
language: python
dist: focal
matrix:
    include:
      # Historically, we've run tests on the latest supported version of Python first.
      # For now, we're running Python 3.12 first, because it's the verions currently used for codegen.
      # This is where additional tests are run so we give it more time.
      - python: "3.12"
      - python: "3.9"
      - python: "3.10"
      - python: "3.11"
      - python: "3.13"

install:
  - travis_retry sudo apt-get -y install python3-pip
  - travis_retry pip install --upgrade pip
  # tox 4.0 broke plugin compatibility
  # TODO(ni-jfitzger): When tox-travis has a release compatible with tox>=4.0, remove the tox version specifier (Tracked on GitHub by #1876)
  - travis_retry pip install --upgrade tox==3.* tox-travis

before_script:
  - python tools/ensure_codegen_up_to_date.py

script:
  - tox -c tox-travis.ini

after_success:
  # Install and verify codecov tool
  - travis_retry curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
  - travis_retry curl -Os https://uploader.codecov.io/latest/linux/codecov  # download codecov tool
  - travis_retry curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
  - travis_retry curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
  - travis_retry gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
  - travis_retry shasum -a 256 -c codecov.SHA256SUM
  - travis_retry chmod +x codecov
  # upload coverage
  - travis_retry ./codecov --flags codegenunittests --file codegen.xml
  - travis_retry ./codecov --flags nifakeunittests --file nifakeunittest.xml
  - travis_retry ./codecov --flags nidcpowerunittests --file nidcpowerunittest.xml
  - travis_retry ./codecov --flags nidigitalunittests --file nidigitalunittest.xml
  - travis_retry ./codecov --flags nimodinstunittests --file nimodinstunittest.xml
  - travis_retry ./codecov --flags niscopeunittests --file niscopeunittest.xml
  - travis_retry ./codecov --flags nitclkunittests --file nitclkunittest.xml
