sudo: false
cache: pip
dist: trusty
language: python
# For pypy versions, see https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build
python: 
  - "pypy-5.6.0"
  - "pypy3.5-5.8.0"
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install --upgrade tox 
  - pip install --upgrade tox-travis 
  - pip install --upgrade coveralls

script:
  - make clean
  - tox -e codegen PRINT=1 PYTHON_CMD=python
  - tox
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then tox -e flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then tox -e docs; fi

#after_success:
#  - coveralls


