group: travis_latest
language: python
dist: focal
matrix:
    include:
      # We run tests on the latest supported version of Python first.
      # This is where additional tests are run so we give it more time.
      - python: "3.10"
      - python: "3.7"
      - python: "3.8"
      - python: "3.9"

install:
  - travis_retry sudo apt-get -y install python3-pip
  - travis_retry pip install --upgrade pip
  # tox 4.0 broke plugin compatibility
  # TODO(ni-jfitzger): When tox-travis has a release compatible with tox>=4.0, remove the tox version specifier (Tracked on GitHub by #1876)
  - travis_retry pip install --upgrade tox==3.* tox-travis codecov

before_script:
  - python tools/ensure_codegen_up_to_date.py

script:
  - tox -c tox-travis.ini

after_success:
  - travis_retry codecov --flags codegenunittests --file codegen.xml
  - travis_retry codecov --flags nifakeunittests --file nifakeunittest.xml
  - travis_retry codecov --flags nidcpowerunittests --file nidcpowerunittest.xml
  - travis_retry codecov --flags nidigitalunittests --file nidigitalunittest.xml
  - travis_retry codecov --flags nimodinstunittests --file nimodinstunittest.xml
  - travis_retry codecov --flags nitclkunittests --file nitclkunittest.xml
