sudo: false
cache: pip
dist: trusty
language: python
# For pypy versions, see https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
  - "pypy3.5-5.8.0"
  - "pypy-5.6.0"

install:
  - pip install --upgrade tox tox-travis coveralls

script:
  - tox -e clean,build_test,codegen PRINT=1 PYTHON_CMD=python
  - tox -e test

after_success:
  - coveralls


