sudo: false
cache: pip
dist: trusty
language: python
# For pypy versions, see https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build
python: 
  - flake8
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - "pypy-5.6.0"
  - "pypy3.5-5.8.0"

install:
  - pip install --upgrade setuptools mako mock tox tox-travis flake8

#before_script:
#  - flake8

script:
  - make clean all test PRINT=1 PYTHON_CMD=python




