group: travis_latest
language: python
matrix:
    include:
      # We run Python 3.9 based tests towards the start. This is where additional tests are run so we give it more time
      - python: 3.9
      - python: 3.6
      - python: 3.7
      - python: 3.8

install:
  - travis_retry sudo apt-get -y install python3-pip
  - travis_retry pip install --upgrade pip
  - travis_retry pip install --upgrade tox tox-travis codecov

before_script:
  - python tools\ensure_codegen_up_to_date.py

script:
  - tox -c tox-travis.ini

after_success:
  - travis_retry codecov --flags codegenunittests --file codegen.xml
  - travis_retry codecov --flags nifakeunittests --file nifakeunittest.xml
  - travis_retry codecov --flags nidigitalunittests --file ninidigitalunittest.xml
  - travis_retry codecov --flags nimodinstunittests --file nimodinstunittest.xml
  - travis_retry codecov --flags nitclkunittests --file nitclkunittest.xml
