group: travis_latest
language: python
matrix:
    include:
      # We put pypy at the beginning because for some reason the build takes much longer, this starts it earlier 
      # so multiple others can be running while these continue to run.
      - python: pypy3
      # We run Python 3.8 based tests towards the start. This is where additional tests are run so we give it more time
      - python: 3.8
        dist: xenial
        sudo: true
      # End Python 3.8 based tests
      - python: 3.5
      - python: 3.6
      # Python 3.7+ needs OpenSSL 1.0.2+ which isn't supported on trusty - use xenial and sudo: true based on workarounds
      # in Travis issues (this is from multiple issues)
      - python: 3.7
        dist: xenial
        sudo: true
      # - python: nightly
      #   dist: xenial
      #   sudo: true
    # No prerelease tests at this point
    # allow_failures:
      # Allow tests using under development builds of Python to fail without failing the PR/change
      # - python: nightly

install:
  - travis_retry sudo apt-get -y install python3-pip
  - travis_retry pip install --upgrade pip
  - travis_retry pip install --upgrade tox tox-travis python-coveralls


script:
  - tox -c tox-travis.ini

after_success:
  - travis_retry coveralls --coveralls_yaml .coveralls-travis.yml --config_file tools/coverage_unit_tests.rc

